import { createServer } from 'node:http';

const statuses = ['running', 'completed', 'failed', 'interrupted'] as const;
type AgentStatus = (typeof statuses)[number];
type AgentPhase = 'queued' | 'active';
interface AgentMetric {
    name: string;
    type: string;
    index: number;
    status: AgentStatus;
    phase: AgentPhase;
    outputTokens: number;
    lastTurnOutputTokens?: number;
    turns: number;
    contextTokens?: number;
    maxTokensClampedFrom?: number;
    maxTokensClampedTo?: number;
    activeToolCalls: number;
}

function escapeLabel(value: string): string {
    return value.replaceAll('\\', '\\\\').replaceAll('\n', '\\n').replaceAll('"', '\\"');
}

/** Run-scoped, content-free metrics. Terminal agents remain visible until shutdown. */
export class AgentMetrics {
    private readonly agents = new Map<string, AgentMetric>();

    private readonly runId: string;

    constructor(runId: string) {
        this.runId = runId;
    }

    queue(name: string, type: string): void {
        this.upsert(name, type, 'queued');
    }

    start(name: string, type: string): void {
        this.upsert(name, type, 'active');
    }

    finish(name: string, status: AgentStatus): void {
        const agent = this.agents.get(name);
        if (agent) {
            agent.status = status;
            agent.activeToolCalls = 0;
        }
    }

    startToolCall(name: string): void {
        const agent = this.agents.get(name);
        if (agent) agent.activeToolCalls += 1;
    }

    finishToolCall(name: string): void {
        const agent = this.agents.get(name);
        if (agent) agent.activeToolCalls = Math.max(0, agent.activeToolCalls - 1);
    }

    incrementTurns(name: string): void {
        const agent = this.agents.get(name);
        if (agent) agent.turns += 1;
    }

    addOutputTokens(name: string, tokens: number | undefined): void {
        const agent = this.agents.get(name);
        if (!agent) return;
        if (tokens !== undefined && Number.isFinite(tokens) && tokens >= 0) {
            agent.outputTokens += tokens;
            agent.lastTurnOutputTokens = tokens;
        } else {
            delete agent.lastTurnOutputTokens;
        }
    }

    setContextTokens(name: string, tokens: number | undefined): void {
        const agent = this.agents.get(name);
        if (agent && tokens !== undefined && Number.isFinite(tokens) && tokens >= 0)
            agent.contextTokens = tokens;
    }

    setMaxTokensClamped(name: string, from: unknown, to: unknown): void {
        const agent = this.agents.get(name);
        if (!agent) return;
        if (isNonNegativeNumber(from)) agent.maxTokensClampedFrom = from;
        if (isNonNegativeNumber(to)) agent.maxTokensClampedTo = to;
    }

    render(): string {
        const definitions = [
            ['flue_agent_active', 'gauge', 'Whether the agent is currently executing (1 or 0).'],
            ['flue_agent_index', 'gauge', 'One-based agent creation index and queued/active phase, exported only while running.'],
            ['flue_agent_status', 'gauge', 'One-hot agent lifecycle status.'],
            ['flue_agent_context_tokens', 'gauge', 'Latest reported input context size in tokens.'],
            ['flue_agent_output_tokens_total', 'counter', 'Reported output tokens generated by the agent.'],
            ['flue_agent_last_turn_output_tokens', 'gauge', 'Reported output tokens for the latest completed model turn.'],
            ['flue_agent_turns_total', 'counter', 'Completed model turns for the agent.'],
            ['flue_agent_max_tokens_clamped_from', 'gauge', 'Latest requested output-token limit before provider clamping.'],
            ['flue_agent_max_tokens_clamped_to', 'gauge', 'Latest output-token limit after provider clamping.'],
            ['flue_agent_tool_calls_active', 'gauge', 'Tool calls currently active for the agent.'],
        ];
        const lines: string[] = [];
        for (const [metric, type, help] of definitions) {
            lines.push(`# HELP ${metric} ${help}`, `# TYPE ${metric} ${type}`);
            for (const agent of this.agents.values()) {
                const labels = `run_id="${escapeLabel(this.runId)}",agent_name="${escapeLabel(agent.name)}",agent_type="${escapeLabel(agent.type)}"`;
                if (metric === 'flue_agent_status') {
                    for (const status of statuses)
                        lines.push(`${metric}{${labels},status="${status}"} ${Number(agent.status === status)}`);
                } else if (metric === 'flue_agent_index') {
                    if (agent.status === 'running')
                        lines.push(`${metric}{${labels},status="${agent.phase}"} ${agent.index}`);
                } else if (metric === 'flue_agent_context_tokens') {
                    if (agent.contextTokens !== undefined)
                        lines.push(`${metric}{${labels}} ${agent.contextTokens}`);
                } else if (metric === 'flue_agent_last_turn_output_tokens') {
                    if (agent.lastTurnOutputTokens !== undefined)
                        lines.push(`${metric}{${labels}} ${agent.lastTurnOutputTokens}`);
                } else if (metric === 'flue_agent_max_tokens_clamped_from') {
                    if (agent.maxTokensClampedFrom !== undefined)
                        lines.push(`${metric}{${labels}} ${agent.maxTokensClampedFrom}`);
                } else if (metric === 'flue_agent_max_tokens_clamped_to') {
                    if (agent.maxTokensClampedTo !== undefined)
                        lines.push(`${metric}{${labels}} ${agent.maxTokensClampedTo}`);
                } else {
                    const value = metric === 'flue_agent_active'
                        ? Number(agent.status === 'running' && agent.phase === 'active')
                        : metric === 'flue_agent_turns_total'
                            ? agent.turns
                            : metric === 'flue_agent_tool_calls_active'
                                ? agent.activeToolCalls
                                : agent.outputTokens;
                    lines.push(`${metric}{${labels}} ${value}`);
                }
            }
        }
        return `${lines.join('\n')}\n`;
    }

    private upsert(name: string, type: string, phase: AgentPhase): void {
        const previous = this.agents.get(name);
        this.agents.set(name, {
            name,
            type,
            index: previous?.index ?? this.agents.size + 1,
            status: 'running',
            phase,
            outputTokens: previous?.outputTokens ?? 0,
            lastTurnOutputTokens: previous?.lastTurnOutputTokens,
            turns: previous?.turns ?? 0,
            contextTokens: previous?.contextTokens,
            maxTokensClampedFrom: previous?.maxTokensClampedFrom,
            maxTokensClampedTo: previous?.maxTokensClampedTo,
            activeToolCalls: previous?.activeToolCalls ?? 0,
        });
    }
}

function isNonNegativeNumber(value: unknown): value is number {
    return typeof value === 'number' && Number.isFinite(value) && value >= 0;
}

export function metricsPort(env: NodeJS.ProcessEnv): number | undefined {
    const value = env.FLUE_METRICS_PORT;
    if (value === undefined) return undefined;
    if (!/^\d+$/.test(value) || Number(value) > 65535)
        throw new Error('FLUE_METRICS_PORT must be an integer from 0 to 65535');
    return Number(value);
}

/** Loopback-only by default; port 0 lets embedded callers select a free port. */
export async function startMetricsServer(metrics: AgentMetrics, port: number) {
    const server = createServer((request, response) => {
        if (request.url !== '/metrics') {
            response.writeHead(404).end();
        } else if (request.method !== 'GET') {
            response.writeHead(405, { Allow: 'GET' }).end();
        } else {
            response.writeHead(200, {
                'Content-Type': 'text/plain; version=0.0.4; charset=utf-8',
                'Cache-Control': 'no-store',
            }).end(metrics.render());
        }
    });
    await new Promise<void>((resolve, reject) => {
        server.once('error', reject);
        server.listen(port, '127.0.0.1', () => {
            server.removeListener('error', reject);
            resolve();
        });
    });
    const address = server.address();
    if (!address || typeof address === 'string') throw new Error('Metrics server has no TCP address');
    return {
        port: address.port,
        close: () => new Promise<void>((resolve, reject) => {
            server.close((error) => error ? reject(error) : resolve());
            server.closeAllConnections();
        }),
    };
}
